language: perl6
perl6:
  - latest
install:
  - rakudobrew build-zef
  - zef --debug --depsonly install .
services:
  - postgresql
before_script:
  - cp config/application.json-travis config/application.json
  - psql -c 'create database travis_ci_test;' -U postgres
  - perl6 -Ilib bin/ar
