on: [push]

jobs:
  test:
    runs-on: ubuntu-20.04
    services:
      postgres:
        image: postgres:12
        ports:
          - 5432:5432
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5
    name: Tests
    steps:
    - name: Checkout
      uses: actions/checkout@v1
    - name: Setup database
      run: |
        cp config/database.yml.github-actions config/database.yml
        cp config/application.json.github-actions config/application.json
    - name: Runs tests
      id: tests
      uses: JJ/raku-container-action@master
      env:
        RAILS_ENV: test
        POSTGRES_USER: postgres
        POSTGRES_PASSWORD: postgres
