on: [push]

jobs:
  test:
    runs-on: ubuntu-20.04
    services:
      postgres:
        image: postgres:12
        ports:
          - 5432:5432
        env:
          POSTGRES_DB: ar_test
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5
    name: Tests
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Install Raku
      uses: Raku/setup-raku@v1
      with:
        raku-version: 'latest'
    - name: Install Dependencies
      run: zef install --/test --test-depends --deps-only .
    - name: Install App::Prove6
      run: zef install --/test App::Prove6
    - name: Configure database
      run: cp config/application.json.github-actions config/application.json
    - name: Migrate database
      run: raku -Ilib bin/ar
    - name: Run Tests
      run: prove6 -l t
